apiVersion: apps/v1
kind: Deployment
metadata:
  name: productsvc
spec:
  selector:
    matchLabels:
      app: productsvc
  template:
    metadata:
      labels:
        app: productsvc
    spec:
      containers:
        - name: productsvc
          image: {{ .Values.image.name }}
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: {{ .Values.defaultPort }}
